//import Image from 'next/image'
import Head from "next/head";
import Image from "next/image";

//image
import profileImage from "../public/p2.png";
import graphicDesign from "../public/design.png";
import code from "../public/code.png";
import image1 from "../public/web1.png";
import image2 from "../public/web2.png";
import image3 from "../public/web3.png";
import image4 from "../public/web4.png";
import image5 from "../public/web5.png";

//framer
//import {motion} from "framer-motion";

//icons
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiOutlineGithub,
  AiFillLinkedin,
  AiOutlineTwitter,
  AiFillFacebook,
} from "react-icons/ai";

//hooks 
//import  {useState, useEffect } from "react";

export default function Home() {
  //function
  //const [darkmode, setdarkmode] = useState(false);
  return (
    // <div className= {darkmode? "dark:" :""}>
    <div>
      <Head>
        <title>Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;0,800;1,600&display=swap');
        </style>
      </Head>
      <main className="font-poppins bg-yellow-50 min-h-screen px-10 md:px-20 lg:px-40">
        {/* nav and hero */}
        <section>
          {/* nav */}
          <nav className="py-10 flex justify-between">
            <h1 className=" text-sm md:text-xl ">Developed by Ishan Senanayaka</h1>
            <ul className=" flex items-center">
              {/* icon */}
              <li>
                <BsFillMoonStarsFill 
                classname="cursor-pointer text-xl mx-5  " 
                //onClick = {() => setdarkmode(!darkmode)}
              />
              </li>
              <li>
                <a
                  href="https://drive.google.com/drive/folders/1_CUPbQOeLRcV7LRgZVV4aieiljVze8UU?usp=drive_link"
                  download={"resume"}
                  className="bg-yellow-400 text-black px-4 py-2 border-none rounded-md"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          {/* hero */}
          <div className=" text-center p-10">
            <h1 className=" text-5xl font-bold text-yellow-400 md:text-6xl lg:text-7xl lg:mb-4">
              Ishan Senanayaka
            </h1>
            <h3 className=" text-2xl py-4 md:text-3xl ">
              Mobile Apps and Website Developer
            </h3>
            <p className=" text-sm py-4 text-gray-400 leading-6 max-w-xl mx-auto  md:text-md  ">
              Welcome to my digital realm! I am a passionate mobile app and
              website developer, dedicated to transforming creative visions into
              interactive realities. With a knack for innovation and a keen eye
              for detail, I specialize in crafting seamless user experiences
              that captivate and engage. Whether it's building intuitive mobile
              apps or designing dynamic websites, I thrive on bringing ideas to
              life in the digital landscape. Join me on a journey where
              imagination meets technology, and let's turn your digital dreams
              into stunning, functional masterpieces.
            </p>
          </div>
          {/* socials */}
          <div className=" text-5xl flex justify-center gap-16 text-gray-600">
            <a href="https://github.com/Mishan20 ">
              <AiOutlineGithub />
            </a>

            <a href="https://www.linkedin.com/in/ishan-senanayaka-936b44267/ ">
              <AiFillLinkedin />
            </a>

            <a href="https://twitter.com/Senanayaka38949 ">
              <AiOutlineTwitter />
            </a>

            <a href="https://www.facebook.com/profile.php?id=100070423373473 ">
              <AiFillFacebook />
            </a>
          </div>
          {/* profile */}
          {/* <motion.div
            initial ={{ opacity:0 , scale: 0.5}}
            animate = {{opacity:1 , scale: 1}}
            transition ={{duration: 0.5}}
          > */}
          <div className="m-auto relative bg-gradient-to-b from-yellow-200 w-80 h-80 p-5 mt-20 rounded-full">
            <Image
              src={profileImage}
              alt="profile image"
              layout="fill"
              objectFit="cover"
            />
          </div>
          {/* </motion.div> */}
          </section>
          
        
        {/* services */}
        <section>
          <div>
            <h2 className=" text-5xl py-10 font-bold opacity-60 " >
              Services I Offer
            </h2>
            <p className=" text-sm py-2 text-gray-400 leading-6 ">
              Welcome to my digital realm! I am a passionate mobile app and
              website developer, dedicated to transforming creative visions into
              interactive realities. With a knack for innovation and a keen eye
              for detail, I specialize in crafting seamless user experiences
              that captivate and engage. Whether it's building intuitive mobile
              apps or designing dynamic websites, I thrive on bringing ideas to
              life in the digital landscape. Join me on a journey where
              imagination meets technology, and let's turn your digital dreams
              into stunning, functional masterpieces.
            </p>
          </div>
          {/* services cards */}
          <div className=" md:flex lg:flex gap-10 mx-auto">
            {/* card */}
            {/* <motion.div
            whileHover={{scale:1.1}}
            whileTap={{scale: 0.9}}
            > */}
            <div className="bg-yellow-300 text-center shadow-sm p-5 rounded-xl my-10">
              <Image
                src={graphicDesign}
                alt="design image"
                width={100}
                height={100}
                className=" inline"
              />

              <h2 className=" text-2xl font-bold">Graphic Designing</h2>
              <p className=" text-sm py-2 text-gray-800 leading-6">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi
                sint impedit iusto minus quia, eveniet fugit repellat distinctio
                dolores mollitia, eligendi eaque ipsa aliquid ipsum nulla, quod
                iure maiores odio!
              </p>
            </div>
            {/* </motion.div> */}

            {/* card */}
            {/* <motion.div
            whileHover={{scale:1.1}}
            whileTap={{scale: 0.9}}
            > */}
            <div className="bg-yellow-300 text-center shadow-sm p-5 rounded-xl my-10">
              <Image
                src={code}
                alt="design image"
                width={100}
                height={100}
                className=" inline"
              />

              <h2 className=" text-2xl font-bold">Graphic Designing</h2>
              <p className=" text-sm py-2 text-gray-800 leading-6">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi
                sint impedit iusto minus quia, eveniet fugit repellat distinctio
                dolores mollitia, eligendi eaque ipsa aliquid ipsum nulla, quod
                iure maiores odio!
              </p>
            </div>
            {/* </motion.div> */}

            {/* card */}
            {/* <motion.div
            whileHover={{scale:1.1}}
            whileTap={{scale: 0.9}}
            > */}
            <div className="bg-yellow-300 text-center shadow-sm p-5 rounded-xl my-10">
              <Image
                src={graphicDesign}
                alt="design image"
                width={100}
                height={100}
                className=" inline"
              />

              <h2 className=" text-2xl font-bold">Graphic Designing</h2>
              <p className=" text-sm py-2 text-gray-800 leading-6">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi
                sint impedit iusto minus quia, eveniet fugit repellat distinctio
                dolores mollitia, eligendi eaque ipsa aliquid ipsum nulla, quod
                iure maiores odio!
              </p>
            </div>
            {/* </motion.div> */}
          </div>
        </section>

        {/* my work */}
        <section>
          <div>
            <h2 className=" text-5xl py-10 font-bold opacity-60">Portfolio</h2>
            <p className=" text-sm py-2 text-gray-800 leading-6">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi sint
              impedit iusto minus quia, eveniet fugit repellat distinctio
              dolores mollitia, eligendi eaque ipsa aliquid ipsum nulla, quod
              iure maiores odio!
            </p>
          </div>
          {/* images */}
          <div className=" flex flex-col gap-10 p-10 lg:flex-row lg:flex-wrap">
            <div className=" basis-1/3 flex-1" >
            {/* <motion.div
            whileHover={{scale:1.1 , rotate: 3}}
            whileTap={{scale: 0.9 , rotate: 3 , borderRadius: "100%"}} 
            > */}
            <Image
              src={image1}
              alt="image 1"
              layout=" responsive"
              className="rounded-lg object-cover"
            />
            {/* </motion.div> */}
            </div>

            <div className=" basis-1/3 flex-1">
            {/* <motion.div
            whileHover={{scale:1.1 , rotate: 3}}
            whileTap={{scale: 0.9 , rotate: 3 , borderRadius: "100%"}} 
            > */}
            <Image
              src={image2}
              alt="image 1"
              layout=" responsive"
              className="rounded-lg object-cover"
            />
            {/* </motion.div> */}
            </div>
            

            <div className=" basis-1/3 flex-1">
            {/* <motion.div
            whileHover={{scale:1.1 , rotate: 3}}
            whileTap={{scale: 0.9 , rotate: 3 , borderRadius: "100%"}} 
            > */}
            <Image
              src={image3}
              alt="image 1"
              layout=" responsive"
              className="rounded-lg object-cover"
            />
            {/* </motion.div> */}
            </div>

            <div className=" basis-1/3 flex-1">
            {/* <motion.div
            whileHover={{scale:1.1 , rotate: 3}}
            whileTap={{scale: 0.9 , rotate: 3 , borderRadius: "100%"}} 
            > */}
            <Image
              src={image4}
              alt="image 1"
              layout=" responsive"
              className="rounded-lg object-cover"
            />
            {/* </motion.div> */}
            </div>

            <div className=" basis-1/3 flex-1">
            {/* <motion.div
            whileHover={{scale:1.1 , rotate: 3}}
            whileTap={{scale: 0.9 , rotate: 3 , borderRadius: "100%"}} 
            > */}
            <Image
              src={image5}
              alt="image 1"
              layout=" responsive"
              className="rounded-lg object-cover"
            />
            {/* </motion.div> */}
            </div>

            <div className=" basis-1/3 flex-1">
            {/* <motion.div
            whileHover={{scale:1.1 , rotate: 3}}
            whileTap={{scale: 0.9 , rotate: 3 , borderRadius: "100%"}} 
            > */}
            <Image
              src={image1}
              alt="image 1"
              layout=" responsive"
              className="rounded-lg object-cover"
            />
            {/* </motion.div> */}
            </div>
          </div>
        </section>

        {/* footer */}
        <footer className=" border-t-2 border-black text-sm opacity-70 flex flex-col gap-5 items-center justify-center py-10 lg:flex-row lg:items-center  dark: border-white">
          <div>
            <h3 className=" text-base mb-2"> Contact me for more details</h3>
            <p className=" opacity-40">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi sint
              impedit iusto minus quia, eveniet fugit repellat distinctio
              dolores mollitia, eligendi eaque ipsa aliquid ipsum nulla, quod
              iure maiores odio!
            </p>
          </div>
          <div>
            <div className=" text-5xl flex justify-center gap-16 text-gray-600">
              <a href="https://github.com/Mishan20 ">
                <AiOutlineGithub />
              </a>

              <a href="https://www.linkedin.com/in/ishan-senanayaka-936b44267/ ">
                <AiFillLinkedin />
              </a>

              <a href="https://twitter.com/Senanayaka38949 ">
                <AiOutlineTwitter />
              </a>

              <a href="https://www.facebook.com/profile.php?id=100070423373473 ">
                <AiFillFacebook />
              </a>
            </div>
          </div>
        </footer>
      </main>
    </div>
  );
}



