//import Image from 'next/image'
import Head from "next/head"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio Website</title>
        <meta name = "description" content="Generated by create next app"/>
        <link rel= "icon" href = "/favicon.ico" />
        <style>
           @import 
           url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;0,800;1,600&display=swap');
        </style>
      </Head>
      <main className="font-poppins">
        <h1 className="bg-red-500 text-4xl"> Hello World</h1>
      </main>
    </div>
  );
}
